# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dda3c98d02313f8a86648cd0a866a7e9"
name = "Omnis-backend-dev-test1"
handle = "omnis-backend-dev-test1"
application_url = "https://id-glasses-officers-formal.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://id-glasses-officers-formal.trycloudflare.com/auth/callback",
  "https://id-glasses-officers-formal.trycloudflare.com/auth/shopify/callback",
  "https://id-glasses-officers-formal.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "omnis-test1.myshopify.com"
automatically_update_urls_on_dev = true
